void buildFoodDrinkMenuOptions();
void runRathskeller();
void processMenuInput();
void displayModuleText();
void leaveTip();
void orderFoodDrink();
void chooseFoodDrinkMenuItem();
void consumeFoodDrinkItem(int foodDrinkItem);
void updateFoodConsumption();
void checkForNPC();
void addRathskellerToMap();
void setGreetingText();
void playRathskellerMusic();
